name: Anchor Devnet Build & Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - "anchor/**"
      - ".github/workflows/anchor-devnet-deploy.yml"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      SOLANA_WALLET: ${{ secrets.SOLANA_WALLET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Prepare Solana wallet
        if: ${{ env.SOLANA_WALLET != '' }}
        shell: bash
        run: |
          mkdir -p ~/.config/solana
          echo '${{ secrets.SOLANA_WALLET }}' > ~/.config/solana/id.json
          chmod 600 ~/.config/solana/id.json

      - name: Locate Anchor project
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          ROOT="${{ github.workspace }}"
          FOUND=$(find "$ROOT" -maxdepth 4 -type f -name Anchor.toml | head -n1 || true)
          if [ -z "$FOUND" ]; then
            echo "No Anchor project found. Skipping build/deploy steps."
            echo "ANCHOR_DIR=" >> $GITHUB_ENV
            echo "anchor_dir=" >> $GITHUB_OUTPUT
          else
            ANCHOR_DIR=$(dirname "$FOUND")
            echo "Anchor dir: $ANCHOR_DIR"
            echo "ANCHOR_DIR=$ANCHOR_DIR" >> $GITHUB_ENV
            echo "anchor_dir=$ANCHOR_DIR" >> $GITHUB_OUTPUT
          fi

      - name: Pull Anchor Docker image
        run: docker pull solanafoundation/anchor:v0.32.1

      - name: Show Anchor CLI version (in container)
        run: docker run --rm solanafoundation/anchor:v0.32.1 anchor --version

      - name: Keys sync to update Program IDs
        if: ${{ steps.locate.outputs.anchor_dir != '' && env.SOLANA_WALLET != '' }}
        run: |
          docker run --rm \
            -v ${{ steps.locate.outputs.anchor_dir }}:/work \
            -v $HOME/.config/solana:/root/.config/solana \
            -w /work \
            solanafoundation/anchor:v0.32.1 anchor keys sync

      - name: Build (verifiable in Docker)
        if: ${{ steps.locate.outputs.anchor_dir != '' }}
        run: |
          set -euo pipefail
          mkdir -p /tmp
          docker run --rm \
            -v ${{ steps.locate.outputs.anchor_dir }}:/work \
            -w /work \
            solanafoundation/anchor:v0.32.1 anchor build -vv 2>&1 | tee /tmp/anchor_build.log

      - name: Deploy to devnet
        if: ${{ steps.locate.outputs.anchor_dir != '' && env.SOLANA_WALLET != '' }}
        run: |
          docker run --rm \
            -v ${{ steps.locate.outputs.anchor_dir }}:/work \
            -v $HOME/.config/solana:/root/.config/solana \
            -w /work \
            solanafoundation/anchor:v0.32.1 anchor deploy -vv

      - name: Program keys list
        if: ${{ steps.locate.outputs.anchor_dir != '' }}
        run: |
          docker run --rm \
            -v ${{ steps.locate.outputs.anchor_dir }}:/work \
            -w /work \
            solanafoundation/anchor:v0.32.1 anchor keys list

      - name: Note
        if: ${{ steps.locate.outputs.anchor_dir == '' }}
        run: |
          echo "Workflow finished without Anchor project. Add your Anchor program repo and re-run."
      - name: Debug workspace manifests and layout
        if: ${{ steps.locate.outputs.anchor_dir != '' }}
        run: |
          set -euo pipefail
          mkdir -p /tmp
          echo "ANCHOR_DIR=${{ steps.locate.outputs.anchor_dir }}" | tee /tmp/workspace_debug.log
          ls -la "${{ steps.locate.outputs.anchor_dir }}" | tee -a /tmp/workspace_debug.log
          [ -f "${{ steps.locate.outputs.anchor_dir }}/Anchor.toml" ] && cat "${{ steps.locate.outputs.anchor_dir }}/Anchor.toml" | tee -a /tmp/workspace_debug.log || true
          [ -f "${{ steps.locate.outputs.anchor_dir }}/Cargo.toml" ] && cat "${{ steps.locate.outputs.anchor_dir }}/Cargo.toml" | tee -a /tmp/workspace_debug.log || true
          ls -la "${{ steps.locate.outputs.anchor_dir }}/programs" | tee -a /tmp/workspace_debug.log || true
          ls -la "${{ steps.locate.outputs.anchor_dir }}/programs/levr_bet" | tee -a /tmp/workspace_debug.log || true
          [ -f "${{ steps.locate.outputs.anchor_dir }}/programs/levr_bet/Cargo.toml" ] && cat "${{ steps.locate.outputs.anchor_dir }}/programs/levr_bet/Cargo.toml" | tee -a /tmp/workspace_debug.log || true
      - name: Upload workspace debug
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: workspace-debug
          path: /tmp/workspace_debug.log
      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: anchor-build-logs
          path: /tmp/anchor_build.log