name: Anchor Devnet Build & Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - "anchor/**"
      - ".github/workflows/anchor-devnet-deploy.yml"
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Prepare Solana wallet
        shell: bash
        run: |
          mkdir -p ~/.config/solana
          echo '${{ secrets.SOLANA_WALLET }}' > ~/.config/solana/id.json
          chmod 600 ~/.config/solana/id.json

      - name: Locate Anchor project
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          ROOT="${{ github.workspace }}"
          FOUND=$(find "$ROOT" -maxdepth 4 -type f -name Anchor.toml | head -n1 || true)
          if [ -z "$FOUND" ]; then
            echo "No Anchor project found. Skipping build/deploy steps."
            echo "ANCHOR_DIR=" >> $GITHUB_ENV
          else
            ANCHOR_DIR=$(dirname "$FOUND")
            echo "Anchor dir: $ANCHOR_DIR"
            echo "ANCHOR_DIR=$ANCHOR_DIR" >> $GITHUB_ENV
          fi

      - name: Pull Anchor Docker image
        run: docker pull solanafoundation/anchor:v0.32.1

      - name: Show Anchor CLI version (in container)
        run: docker run --rm solanafoundation/anchor:v0.32.1 anchor --version

      - name: Keys sync to update Program IDs
        if: env.ANCHOR_DIR != ''
        run: |
          docker run --rm \
            -v ${{ env.ANCHOR_DIR }}:/work \
            -v $HOME/.config/solana:/root/.config/solana \
            -w /work \
            solanafoundation/anchor:v0.32.1 anchor keys sync

      - name: Build (verifiable in Docker)
        if: env.ANCHOR_DIR != ''
        run: |
          docker run --rm \
            -v ${{ env.ANCHOR_DIR }}:/work \
            -v $HOME/.config/solana:/root/.config/solana \
            -w /work \
            solanafoundation/anchor:v0.32.1 anchor build -vv

      - name: Deploy to devnet
        if: env.ANCHOR_DIR != '' && secrets.SOLANA_WALLET != ''
        run: |
          docker run --rm \
            -v ${{ env.ANCHOR_DIR }}:/work \
            -v $HOME/.config/solana:/root/.config/solana \
            -w /work \
            solanafoundation/anchor:v0.32.1 anchor deploy -vv

      - name: Program keys list
        if: env.ANCHOR_DIR != ''
        run: |
          docker run --rm \
            -v ${{ env.ANCHOR_DIR }}:/work \
            -v $HOME/.config/solana:/root/.config/solana \
            -w /work \
            solanafoundation/anchor:v0.32.1 anchor keys list

      - name: Note
        if: env.ANCHOR_DIR == ''
        run: |
          echo "Workflow finished without Anchor project. Add your Anchor program repo and re-run."